export const PRODUCTS_ACTION_TYPES = {
    SET_ALL_PRODUCTS: 'SET_ALL_PRODUCTS',
    SET_TECH_PRODUCTS: 'SET_TECH_PRODUCTS',
    SET_CLOTH_PRODUCTS: 'SET_CLOTH_PRODUCTS',
    SET_PRODUCT_DETAIL_IMG: 'SET_PRODUCT_DETAIL_IMG',
   
};