export const CART_ACTION_TYPES = {
    ADD_TO_CART: 'ADD_TO_CART',
    INCREASE_CART_ITEM: 'INCREASE_CART_ITEM',
    DECREASE_CART_ITEM: 'DECREASE_CART_ITEM',
    UPDATE_CART_TOTAL: 'UPDATE_CART_TOTAL',
    UPDATE_CART_COUNT: 'UPDATE_CART_COUNT',
    SET_ATTRIBUTE: 'SET_ATTRIBUTE',
    UPDATE_ATTRIBUTE: 'UPDATE_ATTRIBUTE',
    SET_SLIDER_MAIN_IMAGE: 'SET_SLIDER_MAIN_IMAGE',
    SET_TAX: 'SET_TAX',
    FLASH_IS_ACTIVE: 'FLASH_IS_ACTIVE',
};